SET DEFINE OFF;
CREATE OR REPLACE FUNCTION FN_GET_ERRMSG_EN(PV_ERRNUM IN VARCHAR2) RETURN VARCHAR2
IS
    L_ERRDESC VARCHAR2(1000);
BEGIN
    L_ERRDESC := PV_ERRNUM;
    BEGIN
        SELECT EN_ERRDESC INTO L_ERRDESC FROM DEFERROR WHERE ERRNUM = PV_ERRNUM;
    EXCEPTION WHEN OTHERS THEN
        L_ERRDESC := PV_ERRNUM;
    END;
    RETURN L_ERRDESC;
END;
/
