SET DEFINE OFF;
CREATE OR REPLACE FUNCTION fn_isdate( PV_DATE IN VARCHAR2)

    RETURN DATE IS
    V_TXDATE DATE;
BEGIN

    BEGIN
        SELECT TO_DATE(PV_DATE,'DD/MM/RRRR') INTO V_TXDATE FROM DUAL;
    EXCEPTION WHEN OTHERS THEN
        SELECT TO_DATE(PV_DATE,'DDMMRRRR') INTO V_TXDATE FROM DUAL;
    END;

    RETURN V_TXDATE;

EXCEPTION
   WHEN OTHERS THEN
    RETURN NULL;
END;
/
