SET DEFINE OFF;
CREATE OR REPLACE FUNCTION FN_RESET_DEVIDENTRATE(pv_TYPERATE In VARCHAR2,pv_DEVIDENTRATE IN VARCHAR2)
    RETURN NUMBER IS
    v_Result  NUMBER(20,10);

BEGIN
    if(pv_TYPERATE='R') THEN
    v_Result:=to_number(pv_DEVIDENTRATE);
    ELSE
    v_Result:=0;
    END IF;

    RETURN v_Result;

EXCEPTION
   WHEN OTHERS THEN
    RETURN 0;
END;
 
 
 
 
/
