SET DEFINE OFF;
CREATE OR REPLACE FUNCTION FN_VSDBREAKSTRING_1711 (PV_STRING IN VARCHAR2) RETURN VARCHAR2 IS
    L_IN_STRING VARCHAR2(2000);
    L_OUT_STRING VARCHAR2(2000);
    L_INSTR NUMBER;
    L_STR_OUT VARCHAR2(2000);
BEGIN
    L_IN_STRING := PV_STRING;
    L_INSTR := INSTR(L_IN_STRING, CHR(10));
    IF L_INSTR > 0 THEN
        IF LENGTH(L_IN_STRING) > L_INSTR THEN
            RETURN FN_VSDBREAKSTRING_1711(SUBSTR(L_IN_STRING, 1, L_INSTR - 1)) || CHR(10) || FN_VSDBREAKSTRING_1711(SUBSTR(L_IN_STRING, L_INSTR + 1));
        ELSE
            RETURN FN_VSDBREAKSTRING_1711(SUBSTR(L_IN_STRING, 1, L_INSTR - 1));
        END IF;
    ELSE
        IF LENGTH(L_IN_STRING) > ERRNUMS.C_MAX_CHAR_PER_ROW THEN
            RETURN SUBSTR(L_IN_STRING, 1, ERRNUMS.C_MAX_CHAR_PER_ROW) || CHR(10) || FN_VSDBREAKSTRING_1711(SUBSTR(L_IN_STRING, ERRNUMS.C_MAX_CHAR_PER_ROW + 1));
        ELSE
            RETURN L_IN_STRING;
        END IF;
    END IF;

    RETURN L_OUT_STRING;
EXCEPTION WHEN OTHERS THEN
    RETURN PV_STRING;
END;
/
