SET DEFINE OFF;
CREATE OR REPLACE FUNCTION FNC_VALIDATE_SCOPE
(
    v_BRID      IN Varchar2,    --CHI NHANH KHACH HANG      CFMAST.BRID
    v_CAREBY    IN Varchar2,    --NHOM CAREBY KHACH HANG    CFMAST.CAREBY
    v_TLSCOPE   IN Varchar2,    --PHAM VI TRUY CAP CUA TELLERID = FNC_CHECK_CMDID_SCOPE('RPTID', 'R', 'TLID')
    v_TLIDBRID  IN Varchar2,    --CHI NHANH CUA TELLER = TLPROFILES.BRID
    v_TLGROUPS  IN Varchar2     --DANH SACH CAC NHOM MA TELLERID TRUC THUOC
)
RETURN NUMBER IS
    v_regionid varchar2(20);
BEGIN

    --CAREBY
    IF INSTR(v_TLGROUPS, v_CAREBY)>0 THEN
        RETURN 0;
    END IF;   
    RETURN -1;
END;
/
