SET DEFINE OFF;
CREATE OR REPLACE FUNCTION GET_SYS_PREWORKINGDATE  (busdate IN DATE)
  RETURN  DATE IS

   getdate  DATE;

BEGIN
SELECT MAX(SBDATE) INTO getdate
FROM SBCLDR
WHERE SBDATE <= busdate
    AND HOLIDAY = 'N'
    AND CLDRTYPE = '000';
 RETURN getdate;
EXCEPTION
   WHEN OTHERS THEN
    RETURN SYSDATE;
END;
/
