SET DEFINE OFF;
CREATE OR REPLACE FUNCTION GETCURRDATE
  RETURN DATE IS
   getdate  DATE;
BEGIN

SELECT TO_DATE(VARVALUE,'DD/MM/YYYY') CURRDATE INTO getdate
FROM SYSVAR
WHERE GRNAME = 'SYSTEM' AND VARNAME ='CURRDATE';

RETURN getdate;
EXCEPTION
   WHEN OTHERS THEN
    RETURN SYSDATE;
END;
/
