SET DEFINE OFF;
CREATE OR REPLACE FUNCTION getworkingdateprev (F_INDATE DATE)
RETURN DATE
IS
    V_NEXTWRKDATE DATE;
BEGIN
    SELECT MAX(SBDATE) INTO V_NEXTWRKDATE FROM SBCLDR WHERE SBDATE <= F_INDATE AND HOLIDAY = 'N' AND CLDRTYPE='000';
    RETURN V_NEXTWRKDATE;
EXCEPTION WHEN OTHERS THEN
    RETURN F_INDATE;
END;

-- END OF DDL SCRIPT FOR FUNCTION HOSTCB.GETNEXTWORKINGDATE
/
