SET DEFINE OFF;
CREATE OR REPLACE FUNCTION getworkingdatenext (F_INDATE DATE)
RETURN DATE
IS
    V_NEXTWRKDATE DATE;
BEGIN
    SELECT MIN(SBDATE) INTO V_NEXTWRKDATE FROM SBCLDR WHERE SBDATE >= F_INDATE AND HOLIDAY = 'N' AND CLDRTYPE = '000';
    RETURN V_NEXTWRKDATE;
EXCEPTION WHEN OTHERS THEN
    RETURN F_INDATE;
END;
/
