SET DEFINE OFF;
CREATE OR REPLACE PROCEDURE gen_export_script(P_ERR_CODE IN OUT VARCHAR2, P_ERR_PARAM IN OUT VARCHAR2)
IS

BEGIN
    P_ERR_CODE := 0;
    FOR REC IN (SELECT * FROM EXPORT_SCRIPT_MANAGE)
    LOOP
        EXPORT_SCRIPT(REC.TABLENAME, REC.KEY1, REC.KEY2, REC.KEY3, REC.ORDER1, REC.PATHNAME);
    END LOOP;
EXCEPTION WHEN OTHERS THEN
    P_ERR_CODE := -1;
    PLOG.ERROR ('GEN_EXPORT_SCRIPT: ' || SQLERRM || DBMS_UTILITY.FORMAT_ERROR_BACKTRACE);
END GEN_EXPORT_SCRIPT;
/
