SET DEFINE OFF;
CREATE OR REPLACE PROCEDURE PR_GEN_IMPORT_FIIN (P_TABLENAME VARCHAR2, P_TABLENAMEHIST VARCHAR2, DBNAME VARCHAR2)
IS
    V_FILECODE VARCHAR2(10);
    V_FILECODE_OLD VARCHAR2(10);
    V_DATA_TYPE VARCHAR2(5);

    CURSOR V_CURSOR IS
    SELECT COLUMN_ID, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, AVG_COL_LEN
    FROM USER_TAB_COLS
    WHERE TABLE_NAME = DBNAME || '.' || P_TABLENAME;

    V_ROW V_CURSOR%ROWTYPE;

BEGIN
    
    RETURN;
    BEGIN
        SELECT FILECODE INTO V_FILECODE_OLD FROM FILEMASTER WHERE TABLENAME = DBNAME || '.' || P_TABLENAME;
    EXCEPTION
    WHEN OTHERS THEN
        V_FILECODE_OLD := '';
    END;

    DELETE FROM FILEMASTER WHERE FILECODE = V_FILECODE_OLD;
    DELETE FROM FILEMAP WHERE FILECODE = V_FILECODE_OLD;

    SELECT 'FI' || LPAD(COUNT(1) + 1, 3, '0')
    INTO V_FILECODE
    FROM FILEMASTER
    WHERE FILECODE LIKE 'FI%';

    INSERT INTO FILEMASTER (EORI, FILECODE, FILENAME, FILEPATH, TABLENAME, SHEETNAME, ROWTITLE, DELTD, EXTENTION, PAGE, PROCNAME, PROCFILLTER, OVRRQD, MODCODE, RPTID, CMDCODE, IMPBYINDEX, TABLENAME_HIST)
    VALUES ('I', V_FILECODE, 'IMPORT' || REPLACE(P_TABLENAME,'_TMP',''), NULL, DBNAME || '.' || P_TABLENAME, '1', 1, 'N', '.XLS', 100, '', NULL, 'N', NULL, NULL, 'SA', 'Y', DBNAME || '.' || P_TABLENAMEHIST);

    OPEN V_CURSOR;
    LOOP FETCH V_CURSOR INTO V_ROW;
    EXIT WHEN V_CURSOR%NOTFOUND;
        SELECT CASE WHEN V_ROW.DATA_TYPE = 'VARCHAR2' THEN 'C'
                    WHEN V_ROW.DATA_TYPE = 'NUMBER' THEN 'N'
                    WHEN V_ROW.DATA_TYPE = 'NUMBER' THEN 'D'
               ELSE 'C' END
               INTO  V_DATA_TYPE
        FROM DUAL;

        INSERT INTO FILEMAP (FILECODE,FILEROWNAME,TBLROWNAME,TBLROWTYPE,ACCTNOFLD,TBLROWMAXLENGTH,CHANGETYPE,DELTD,DISABLED,VISIBLE,LSTODR,FIELDDESC,SUMAMT)
        VALUES (V_FILECODE, V_ROW.COLUMN_NAME, V_ROW.COLUMN_NAME, V_DATA_TYPE, 'N', V_ROW.DATA_LENGTH + 10, 'U', 'N', 'Y', 'Y', V_ROW.COLUMN_ID, V_ROW.COLUMN_NAME, 'N');
    END LOOP;

    COMMIT;
EXCEPTION
WHEN OTHERS THEN
    PLOG.ERROR ('PR_GEN_IMPORT_FIIN: ' || SQLERRM || DBMS_UTILITY.FORMAT_ERROR_BACKTRACE);
END;
/
