SET DEFINE OFF;
CREATE OR REPLACE PROCEDURE sp_cr_getbankref (
    PV_REFCURSOR     IN OUT PKG_REPORT.REF_CURSOR,
    PV_STRBANKCODE   IN     VARCHAR2,
    PV_STRTXDATE     IN     VARCHAR2)
IS
    V_STRSQL   VARCHAR2 (2000);
BEGIN
    V_STRSQL :=
           'SELECT USERIDKEY ||' || 'TO_CHAR(TO_DATE('''
        || PV_STRTXDATE
        || ''',''DD/MM/RRRR''),''YYMMDD'') || LPAD(SEQ_BANKREF'
        || PV_STRBANKCODE
        || '.NEXTVAL,6,0) REF FROM CRBDEFBANK WHERE BANKCODE = ''BIDV''';

    OPEN PV_REFCURSOR FOR V_STRSQL;
EXCEPTION
    WHEN OTHERS
    THEN
        RETURN;
END;
 
 
/
