SET DEFINE OFF;
CREATE OR REPLACE FORCE VIEW V_APPMAP_BY_TLTXCD
(TLTXCD, APPTYPE, TBLNAME, APPTXCD, ACFLD, 
 AMTEXP, COND, FLDKEY, ACFLDREF, TXTYPE, 
 FIELD, FLDTYPE, TRANF, OFILE, OFILEACT, 
 ISRUN, FLDRND, TRDESC)
AS 
SELECT M.TLTXCD TLTXCD, M.APPTYPE APPTYPE, T.TBLNAME, M.APPTXCD APPTXCD, M.ACFLD ACFLD, M.AMTEXP AMTEXP, M.COND COND,
    M.FLDKEY, M.ACFLDREF ACFLDREF, T.TXTYPE TXTYPE, T.FIELD FIELD, T.FLDTYPE FLDTYPE, T.TRANF TRANF, T.OFILE OFILE,
    T.OFILEACT, M.ISRUN, T.FLDRND,M.TRDESC
FROM APPMAP M, APPTX T
WHERE M.APPTYPE = T.APPTYPE AND M.APPTXCD =T.TXCD
/
