SET DEFINE OFF;
CREATE OR REPLACE FORCE VIEW VSDTXINFOHIST
(AUTOID, FINFILENAME, SWIFT)
AS 
SELECT L.AUTOID, F.FINFILENAME, F.FINBODY SWIFT
FROM VSD_FIN_LOG F, VSDTRFLOGHIST L
WHERE F.FINFILENAME = L.FINFILENAME
/
