SET DEFINE OFF;
CREATE OR REPLACE FORCE VIEW VSDTXINFO
(AUTOID, FINFILENAME, SWIFT)
AS 
SELECT L.AUTOID, F.FINFILENAME, F.FINBODY SWIFT
FROM VSD_FIN_LOG F, VSDTRFLOG L
WHERE F.FINFILENAME = L.FINFILENAME
/
