SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('BA0003','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT, CHKSCOPECMDSQL) Values   ('BA0003', 'Tra cứu số dư của tất cả NĐT theo TVLK', 'Look up balances of all investors by depository members', 'SELECT TBL.memberCode MEMBERCODE, TBL.accNo ACCNO, TBL.createDate CREATEDATE, TBL.accType ACCTYPE, TBL.accNoRef ACCNOREF, TBL.Afbalance AFBALANCE, TBL.autoid AUTOID, TBL.REQKEY, to_char(TBL.CREATEDATE_AT, ''HH24:MI:SS'') TIMECREATED
FROM (
    SELECT * FROM TBL_BALANCE_LOG
    UNION ALL 
    SELECT * FROM TBL_BALANCE_LOGHIST
) TBL
WHERE 0=0', 'CFMAST_TPRL', 'frmCFMAST', 'TIMECREATED DESC', '    ', 0, 50, 'N', 30, 'NNNNYYYNNNN', 'Y', 'T', '', 'N', '', '');COMMIT;