SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('CUSTODYCD_CF','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT, CHKSCOPECMDSQL) Values   ('CUSTODYCD_CF', 'Thông tin khách hàng', 'Customer information', 'SELECT C.CUSTODYCD, C.FULLNAME, C.ADDRESS, C.DATEOFBIRTH, C.PROVINCE, C.EMAIL, C.IDPLACE, 
    (CASE WHEN SUBSTR(C.CUSTODYCD, 4, 1) = ''F'' THEN C.TRADINGCODE ELSE C.IDCODE END) IDCODE,  
    (CASE WHEN SUBSTR(C.CUSTODYCD, 4, 1) = ''F'' THEN C.TRADINGCODEDT ELSE C.IDDATE END) IDDATE, 
    ''VISD/'' || (CASE WHEN C.IDTYPE = ''001'' THEN ''IDNO''
         WHEN C.IDTYPE = ''002'' THEN ''CCPT''
         WHEN C.IDTYPE = ''005'' THEN ''CORP''
         WHEN C.IDTYPE = ''009'' AND C.CUSTTYPE = ''B'' THEN ''FIIN''
         WHEN C.IDTYPE = ''009'' AND C.CUSTTYPE = ''I'' THEN ''ARNU''
         ELSE ''OTHR'' END) ALTERNATEID,
    CTP.ACCTYPE, CTP.ADTXTYPE, CTP.ADTXINFO, CTP.ADTXFTYPE, C.IDTYPE, C.CUSTTYPE, C.MOBILESMS PHONE, A1.CDCONTENT COUNTRY 
FROM CFMAST C
LEFT JOIN CFMAST_TPRL CTP ON C.CUSTODYCD = CTP.CUSTODYCD
LEFT JOIN (
    SELECT *
    FROM ALLCODE A 
    WHERE CDNAME =  ''NATIONAL''
    AND A.EN_CDCONTENT IS NOT NULL
) A1 ON C.COUNTRY = A1.CDVAL
WHERE C.STATUS = ''A''
AND 0 = 0', 'CUSTODYCD_CF', 'frmCFMAST', '', '', NULL, 5000, 'Y', 30, '', 'Y', 'T', '', 'N', '', '');COMMIT;