SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('BA0001','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT, CHKSCOPECMDSQL) Values   ('BA0001', 'Tra cứu kết quả Nộp/Rút tiền ', '
Look up Deposit/Withdrawal results', 'SELECT C.TXNUM, C.TXDATE, C. PROCESSNUM ,C.TRANSACTIONNO, C.CUSTODYCD, C2.FULLNAME ,C.AMOUNT , C.MSGFEEDBACK, C.REFBANKCODE ,
to_char(C.SENDTIME, ''HH24:MI:SS'') SENDTIME, to_char(C.COMPLETETIME, ''HH24:MI:SS'') COMPLETETIME , C.LASTCHANGE, A.CDCONTENT TRANSTYPE, A1.CDCONTENT STATUS,
C.AUTOID
FROM CIREMITTANCE C
LEFT JOIN CFMAST C2 ON C.CUSTODYCD =C2.CUSTODYCD
LEFT JOIN (SELECT * FROM ALLCODE WHERE CDNAME=''TRANSTYPE'' AND CDTYPE=''ST'') A ON A.CDVAL=C.TRANSTYPE
LEFT JOIN (SELECT * FROM ALLCODE WHERE CDNAME=''TRANSTATUS'' AND CDTYPE=''ST'') A1 ON A1.CDVAL=C.STATUS 
WHERE 1=1', 'CFMAST_TPRL', 'frmCFMAST', 'AUTOID DESC', '    ', 0, 50, 'N', 30, 'NNNNYYYNNNN', 'Y', 'T', '', 'N', '', '');COMMIT;