SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('CF1703','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT, CHKSCOPECMDSQL) Values   ('CF1703', 'Quản lý thông tin khách hàng đăng ký TPRL', 'Look up customer information registered TPRL', 'SELECT CFMAST.*, A1.CDCONTENT ACCTYPE, A1.CDVAL ACCTYPEVAL, A2.CDCONTENT ADTXTYPE, A2.CDVAL ADTXTYPEVAL, A3.CDCONTENT ADTXINFO,
A3.CDVAL ADTXINFOVAL,A4.CDCONTENT ADTXFTYPE, A4.CDVAL ADTXFTYPEVAL, 
TO_CHAR(CFMAST_TPRL.BEGINSTRATEGYDATE, ''DD/MM/RRRR'') BEGINSTRATEGYDATE, 
TO_CHAR(CFMAST_TPRL.ENDSTRATEGYDATE, ''DD/MM/RRRR'') ENDSTRATEGYDATE,
A5.CDCONTENT ITYP, CFMAST_TPRL.ITYP ITYPVAL, A0.CDCONTENT CSTATUS
FROM CFMAST_TPRL
LEFT JOIN CFMAST ON CFMAST_TPRL.CUSTODYCD = CFMAST.CUSTODYCD
LEFT JOIN (SELECT * FROM ALLCODE  WHERE CDNAME = ''CFSTATUS'' AND CDTYPE = ''CF'') A0 ON CFMAST_TPRL.STATUS = A0.CDVAL
LEFT JOIN (SELECT * FROM ALLCODE  WHERE CDNAME = ''TPRL_ACCTYPE'' AND CDTYPE = ''ST'') A1 ON CFMAST_TPRL.ACCTYPE= A1.CDVAL
LEFT JOIN (SELECT * FROM ALLCODE WHERE CDNAME=''ADTX_TYPE'' AND CDTYPE=''ST'') A2 ON CFMAST_TPRL.ADTXTYPE =A2.CDVAL
LEFT JOIN (SELECT * FROM ALLCODE WHERE CDNAME=''ADTX_INFO'' AND CDTYPE=''ST'') A3 ON CFMAST_TPRL.ADTXINFO =A3.CDVAL
LEFT JOIN (SELECT * FROM ALLCODE WHERE CDNAME=''ADTX_FTYPE'' AND CDTYPE=''ST'') A4 ON CFMAST_TPRL.ADTXFTYPE =A4.CDVAL
LEFT JOIN (SELECT * FROM ALLCODE WHERE CDNAME=''PINV_ITYP'' AND CDTYPE=''ST'') A5 ON CFMAST_TPRL.ITYP=A5.CDVAL
WHERE 1=1', 'CF1703', 'frmCF1703', '', '', 0, 50, 'N', 30, 'NNNNYYYNNNN', 'Y', 'T', '', 'N', '', '');COMMIT;