SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('ST9943','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT, CHKSCOPECMDSQL) Values   ('ST9943', 'Tra cứu điện thông báo từ VSD (544, 546)', 'Manage notification messages from VSD (544, 546)', 'SELECT V.VSDREQID REFID, V.VSDMSGDATE VSDMSGDATE,V.CUSTODYCD CUSTODYCD,V.SECTYPE,V.QTTY QTTY,V.VSDSECTYPE,V.DESCRIPTION DESCRIPTION,L.MSGTYPE MTTYPE,
    SUBSTR(V.REFCUSTODYCD,1,3) REFMEMBER,V.REFCUSTODYCD REFCUSTODYCD,V.VSDPROMSG,L.VSDORDERID,
    A3.<@CDCONTENT> IDTYPE, A1.<@CDCONTENT> FROMQTTY, A2.<@CDCONTENT> TOQTTY, TRF.CDCONTENT MTNAME ,
    (CASE WHEN INSTR(''ISIN'', V.SYMBOL)>0 THEN '''' ELSE (CASE WHEN V.SECTYPE = ''PEND'' THEN V.SYMBOL || ''_WTF'' ELSE V.SYMBOL END) END) SYMBOL,
    (CASE WHEN INSTR(''ISIN'',V.SYMBOL)>0 THEN REPLACE(V.SYMBOL,''ISIN '','''') ELSE '''' END) ISIN
FROM (
    SELECT * FROM VSD_MT508_INF
    UNION ALL
    SELECT * FROM VSD_MT508_INF_HIST
) V 
LEFT JOIN (SELECT * FROM ALLCODE WHERE CDTYPE = ''ST'' AND CDNAME = ''FROMSE'') A1  ON V.FROMSE=A1.CDVAL
LEFT JOIN (SELECT * FROM ALLCODE WHERE CDTYPE = ''ST'' AND CDNAME = ''FROMSE'') A2 ON V.TOSE= A2.CDVAL
LEFT JOIN (SELECT * FROM ALLCODE WHERE CDNAME = ''VSDDEALTYPE'') A3 ON V.VSDSECTYPE= A3.CDVAL
LEFT JOIN (
    SELECT TRF.*, TRFDTL.FLDVAL VSDORDERID FROM VSDTRFLOG TRF 
    LEFT JOIN (
        SELECT * FROM VSDTRFLOGDTL WHERE FLDNAME = ''VSDORDERID''
    ) TRFDTL ON TRF.AUTOID = TRFDTL.REFAUTOID
) L ON L.AUTOID = V.VSDMSGID
LEFT JOIN (SELECT TRFCODE,EN_DESCRIPTION EN_CDCONTENT, DESCRIPTION CDCONTENT FROM VSDTRFCODE) TRF ON TRF.TRFCODE = V.VSDPROMSG
WHERE V.VSDPROMSG IN (''544.NEWM.LINK//518.SETR//TRAD.STCO//NPAR'',''546.NEWM.LINK//518.SETR//TRAD.STCO//NPAR'')', 'CFMAST', 'frmMT598', '', '', 0, 50, 'Y', 30, 'NNNNYYYNNNN', 'Y', 'T', '', 'N', '', '');COMMIT;