SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('TTDIENR','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT, CHKSCOPECMDSQL) Values   ('TTDIENR', 'Điện nhận từ VSD', 'Receive from VSD  ', 'SELECT LOG.AUTOID, DTL.CAPTION, LOG.REFMSGID REFAUTOID, DTL.FLDNAME,
(CASE WHEN DTL.FLDNAME = ''ROUND'' THEN (SELECT A.<@CDCONTENT> FROM ALLCODE  A WHERE A.CDNAME = ''ROUNDTYPE'' AND A.CDVAL = DTL.FLDVAL)
      WHEN DTL.FLDNAME = ''VSDPROMSGDTL'' THEN (SELECT A.<@CDCONTENT> FROM ALLCODE  A WHERE A.CDNAME = ''MT_564_INFTYPE'' AND A.CDVAL = DTL.FLDVAL)
      WHEN DTL.FLDNAME = ''CATYPE'' THEN (SELECT A.<@CDCONTENT> FROM ALLCODE  A WHERE A.CDNAME = ''MT_564'' AND A.CDVAL = DTL.FLDVAL)
      WHEN DTL.FLDNAME = ''VSDSECTYPE'' THEN (SELECT A.<@CDCONTENT> FROM ALLCODE  A WHERE A.CDNAME = ''VSDDEALTYPE'' AND A.CDVAL = DTL.FLDVAL)
      ELSE DTL.FLDVAL END) VALUE, DTL.FLDVAL
FROM VSDTRFLOGDTL DTL, VSDTRFLOG LOG
WHERE LOG.AUTOID = DTL.REFAUTOID
AND LOG.AUTOID = ''<$KEYVAL>'' 
ORDER BY DTL.AUTOID', 'ST.TTDIEN', 'frmRECFDEF', '', '', 0, 50, 'N', 30, '', 'Y', 'T', '', 'N', '', '');COMMIT;