SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('CFMAST','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT, CHKSCOPECMDSQL) Values   ('CFMAST', 'Thông tin khách hàng', 'Customer information', 'SELECT T.CUSTODYCD, T.FULLNAME ,T.DATEOFBIRTH , T.IDCODE ,T.IDDATE ,T.IDPLACE ,T.EMAIL, T.PHONE, T.ALTERNATEID ALTERNATEIDVAL, T.ADDRESS, 
    T.COUNTRY_VSD COUNTRY, T.CUSTTYPE ,T.IDTYPE, T.SEX, C.BEGINSTRATEGYDATE, C.ENDSTRATEGYDATE, 
    A.<@CDCONTENT> ALTERNATEID, A1.<@CDCONTENT> ACCTYPE, A2.<@CDCONTENT> ADTXTYPE, A3.<@CDCONTENT> ADTXINFO, A4.<@CDCONTENT> ADTXFTYPE, A5.<@CDCONTENT> PROVINCE, A6.<@CDCONTENT> ITYP
FROM (
    SELECT C.*, ''VISD/'' || (CASE WHEN C.IDTYPE = ''001'' THEN ''IDNO''
         WHEN C.IDTYPE = ''002'' THEN ''CCPT''
         WHEN C.IDTYPE = ''005'' THEN ''CORP''
         WHEN C.IDTYPE = ''009'' AND C.CUSTTYPE = ''B'' THEN ''FIIN''
         WHEN C.IDTYPE = ''009'' AND C.CUSTTYPE = ''I'' THEN ''ARNU''
         ELSE ''OTHR'' END) ALTERNATEID, C.MOBILESMS PHONE, A1.CDCONTENT COUNTRY_VSD
    FROM CFMAST C
    LEFT JOIN (
        SELECT *
        FROM ALLCODE A 
        WHERE CDNAME =  ''NATIONAL''
        AND A.EN_CDCONTENT IS NOT NULL
    ) A1 ON C.COUNTRY = A1.CDVAL
) T
LEFT JOIN CFMAST_TPRL C ON C.CUSTODYCD =T.CUSTODYCD
LEFT JOIN (SELECT * FROM ALLCODE WHERE CDTYPE=''ST'' AND CDNAME=''VSDALTE'') A ON A.CDVAL=T.ALTERNATEID
LEFT JOIN (SELECT * FROM ALLCODE WHERE CDTYPE=''ST'' AND CDNAME=''TPRL_ACCTYPE'') A1 ON A1.CDVAL=C.ACCTYPE
LEFT JOIN (SELECT * FROM ALLCODE WHERE CDTYPE=''ST'' AND CDNAME=''ADTX_TYPE'') A2 ON A2.CDVAL=C.ADTXTYPE
LEFT JOIN (SELECT * FROM ALLCODE WHERE CDTYPE=''ST'' AND CDNAME=''ADTX_INFO'') A3 ON A3.CDVAL=C.ADTXINFO
LEFT JOIN (SELECT * FROM ALLCODE WHERE CDTYPE=''ST'' AND CDNAME=''ADTX_FTYPE'') A4 ON A4.CDVAL=C.ADTXFTYPE
LEFT JOIN (SELECT * FROM ALLCODE WHERE CDTYPE=''CF'' AND CDNAME =  ''PROVINCE'') A5 ON A5.CDVAL= T.PROVINCE
LEFT JOIN (SELECT * FROM ALLCODE WHERE CDNAME=''PINV_ITYP'' AND CDTYPE=''ST'') A6 ON C.ITYP=A6.CDVAL
WHERE 0=0', 'CFMAST', 'frmCFMAST', '', '', 0, 5000, 'Y', 30, '', 'Y', 'T', '', 'N', '', '');COMMIT;