SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('ST9944','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT, CHKSCOPECMDSQL) Values   ('ST9944', 'Tra cứu điện thông báo từ VSD (598)', 'Manage notification messages from VSD (598)', 'SELECT L.REFMSGID REFID,L.MSGTYPE MTTYPE, C.<@CDCONTENT> MTNAME, V.VSDMSGDATE VSDMSGDATE, V.PAYMENTCYCLE PERIOD,
    (CASE WHEN INSTR(''ISIN'',V.SYMBOL)>0 THEN REPLACE(V.SYMBOL,''ISIN '','''') ELSE '''' END) ISIN, 
    (CASE WHEN INSTR(''ISIN'',V.SYMBOL)>0 THEN '''' ELSE V.SYMBOL END) SYMBOL,
    A0.<@CDCONTENT> ISSTYPE, V.PLACEID PLACEID ,V.QTTY QTTY, V.ROOM ROOM, V.DESCRIPTION DESCRIPTION , V.VSDPROMSG_VALUE CATYPE
FROM (
    SELECT * FROM VSD_MT598_INF
    UNION ALL
    SELECT * FROM VSD_MT598_INF_HIST
) V 
LEFT JOIN VSDTRFLOG L ON  V.VSDMSGID = L.AUTOID
LEFT JOIN (SELECT * FROM ALLCODE WHERE CDNAME = ''VSDTYPE_598'' AND CDTYPE = ''SA'') A0 ON V.VSDMSGTYPE = A0.CDVAL
LEFT JOIN (SELECT TRFCODE,EN_DESCRIPTION EN_CDCONTENT, DESCRIPTION CDCONTENT FROM VSDTRFCODE) C ON V.VSDPROMSG = C.TRFCODE', 'CFMAST', 'frmMT598', '', '', 0, 5000, 'Y', 30, 'NNNNYYYNNNN', 'Y', 'T', '', 'N', '', '');COMMIT;