SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('TTDIEN','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT, CHKSCOPECMDSQL) Values   ('TTDIEN', 'Điện gửi VSD', 'Sent to VSD', 'SELECT EXT.CDCONTENT CAPTION,
    CASE WHEN EXT.FLDNAME IN (''IDTYPE'') THEN (SELECT A.CDCONTENT FROM ALLCODE  A WHERE A.CDNAME = ''VSDDEALTYPE'' AND A.CDVAL = DECODE(EXT.FLDTYPE, ''N'', TO_CHAR(NVAL), CVAL))
         WHEN EXT.FLDNAME IN (''ALTERNATEID'') THEN (SELECT A.CDCONTENT FROM ALLCODE  A WHERE A.CDNAME = ''VSDALTE'' AND A.CDVAL = DECODE(EXT.FLDTYPE, ''N'', TO_CHAR(NVAL), CVAL))
         WHEN EXT.FLDNAME IN (''TRANTYPE'') THEN (SELECT A.CDCONTENT FROM ALLCODE  A WHERE A.CDNAME = ''TRANTYPE'' AND A.CDVAL = DECODE(EXT.FLDTYPE, ''N'', TO_CHAR(NVAL), CVAL))
         WHEN EXT.FLDNAME IN (''CONFIRMSTATUS'') THEN (SELECT A.CDCONTENT FROM ALLCODE A WHERE A.CDNAME = ''CONFIRM_STATUS'' AND A.CDVAL = DECODE(EXT.FLDTYPE, ''N'', TO_CHAR(NVAL), CVAL))
         ELSE DECODE(EXT.FLDTYPE, ''N'', TO_CHAR(NVAL), CVAL) END VALUE
FROM (SELECT CAPTION CDCONTENT, EN_CAPTION EN_CDCONTENT, FLDNAME, TRFCODE, OBJNAME ,FLDTYPE FROM VSDTXMAPEXT) EXT, VSDTXREQ REQ, VSDTXREQDTL DTL
WHERE REQ.REQID = DTL.REQID
AND EXT.TRFCODE = REQ.TRFCODE
AND EXT.OBJNAME = REQ.OBJNAME
AND EXT.FLDNAME = DTL.FLDNAME
AND REQ.REQID = <$KEYVAL> 
ORDER BY REQ.REQID DESC', 'ST.TTDIEN', 'frmRECFDEF', '', '', 0, 5000, 'N', 30, '', 'Y', 'T', '', 'N', '', '');COMMIT;