SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('REQ1711CONF','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT, CHKSCOPECMDSQL) Values   ('REQ1711CONF', 'Tra cứu thông tin điện xác nhận phân bổ tiền, TPRL', 'EN: Tra cứu thông tin điện xác nhận phân bổ tiền, TPRL', 'SELECT REQ.REQID, DTL.TOTALACC, DTL.TOTALQTTY, DTL.TOTALAMT, DTL.TRANDATE, DTL.SETTLEMENTDATE, DTL.NOTE
FROM VSDTXREQ REQ
LEFT JOIN (
	SELECT REQID,
		MAX(CASE WHEN FLDNAME = ''TOTALACC'' THEN NVAL ELSE 0 END) TOTALACC,
		MAX(CASE WHEN FLDNAME = ''TOTALQTTY'' THEN NVAL ELSE 0 END) TOTALQTTY,
		MAX(CASE WHEN FLDNAME = ''TOTALAMT'' THEN NVAL ELSE 0 END) TOTALAMT,
		MAX(CASE WHEN FLDNAME = ''TRANDATE'' THEN CVAL ELSE '''' END) TRANDATE,
		MAX(CASE WHEN FLDNAME = ''SETTLEMENTDATE'' THEN CVAL ELSE '''' END) SETTLEMENTDATE,
		MAX(CASE WHEN FLDNAME = ''NOTE'' THEN OCVAL ELSE '''' END) NOTE
	FROM VSDTXREQDTL GROUP BY REQID
) DTL ON REQ.REQID = DTL.REQID
WHERE REQ.TRFCODE = ''598.010.CASH''
AND REQ.REQID NOT IN (
	SELECT REFCODE FROM VSDTXREQ WHERE TRFCODE = ''598.011.CASH'' AND MSGSTATUS = ''F''
)', 'REQ1711CONF', 'frmREQ1711CONF', 'REQID DESC', '    ', 0, 5000, 'Y', 30, '', 'Y', 'T', '', 'N', '', '');COMMIT;