SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('BA0004','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT, CHKSCOPECMDSQL) Values   ('BA0004', 'Danh sách các giao dịch thanh toán TPRL gửi TVLK', 'List of VSD individual bond payment transactions sent to depository members', 'SELECT TBL.*, A.CDCONTENT CSTATUS, to_char(TBL.CREATEDATE_AT, ''HH24:MI:SS'') TIMECREATED
FROM (
	SELECT * FROM TBL_TRANS_LOG 
	UNION ALL 
	SELECT * FROM TBL_TRANS_LOGHIST 
) TBL 
LEFT JOIN (
	SELECT * FROM ALLCODE WHERE CDNAME LIKE ''BANKTRANSTATUS'' AND CDTYPE = ''SA''
) A ON A.CDVAL = TBL.STATUS', 'CFMAST_TPRL', 'frmCFMAST', 'CREATEDATE_AT DESC', '    ', 0, 50, 'N', 30, 'NNNNYYYNNNN', 'Y', 'T', '', 'N', '', '');COMMIT;