SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('TOTAL1711','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT, CHKSCOPECMDSQL) Values   ('TOTAL1711', 'Tra cứu thông tin tổng hợp phân bổ tiền, TPRL', 'EN: Tra cứu thông tin tổng hợp phân bổ tiền, TPRL', 'SELECT MTAMT.*, MTCUS.TOTALACC, MTQTTY.TOTALQTTY
FROM
(
    SELECT TO_CHAR(VSDMSGDATE, ''DD/MM/RRRR'') VSDMSGDATE, SUM(TO_NUMBER(REPLACE(VSDAMT, ''VND'', ''''))) TOTALAMT
    FROM (
        SELECT * FROM VSD_MT518_INF
        UNION ALL
        SELECT * FROM VSD_MT518_INF_HIST
    ) MT518
    WHERE SUBSTR(VSDCUSTODYCD,4,1) NOT IN (''P'',''E'')
    AND NVL(STATUS, ''NEWM'') = ''NEWM''
    AND CONFSTATUS = ''CONF''
    AND CONFREQSTATUS = ''F''
    GROUP BY TO_CHAR(VSDMSGDATE, ''DD/MM/RRRR'')
) MTAMT
LEFT JOIN (
    SELECT MTCUS1.VSDMSGDATE, COUNT(1) TOTALACC
    FROM
    (
        SELECT TO_CHAR(VSDMSGDATE, ''DD/MM/RRRR'') VSDMSGDATE, CUSTODYCD
        FROM (
            SELECT * FROM VSD_MT508_INF
            UNION ALL
            SELECT * FROM VSD_MT508_INF_HIST
        ) MT5081
        WHERE SUBSTR(CUSTODYCD,4,1) NOT IN (''P'',''E'')
        AND VSDPROMSG IN (''544.NEWM.LINK//518.SETR//TRAD.STCO//NPAR'',''546.NEWM.LINK//518.SETR//TRAD.STCO//NPAR'')
        GROUP BY TO_CHAR(VSDMSGDATE, ''DD/MM/RRRR''), CUSTODYCD
    ) MTCUS1
    GROUP BY MTCUS1.VSDMSGDATE
) MTCUS ON MTAMT.VSDMSGDATE = MTCUS.VSDMSGDATE
LEFT JOIN (
    SELECT TO_CHAR(VSDMSGDATE, ''DD/MM/RRRR'') VSDMSGDATE, SUM(TO_NUMBER(QTTY)) TOTALQTTY
    FROM (
        SELECT * FROM VSD_MT508_INF
        UNION ALL
        SELECT * FROM VSD_MT508_INF_HIST
    ) MT5082
    WHERE SUBSTR(CUSTODYCD,4,1) NOT IN (''P'',''E'')
    AND VSDPROMSG IN (''544.NEWM.LINK//518.SETR//TRAD.STCO//NPAR'',''546.NEWM.LINK//518.SETR//TRAD.STCO//NPAR'')
    GROUP BY TO_CHAR(VSDMSGDATE, ''DD/MM/RRRR'')
) MTQTTY ON MTAMT.VSDMSGDATE = MTQTTY.VSDMSGDATE
WHERE 0 = 0', 'TOTAL1711', 'frmTOTAL1711', 'MTAMT.VSDMSGDATE DESC', '    ', 0, 50, 'Y', 30, '', 'Y', 'T', '', 'N', '', '');COMMIT;