SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('VSDTXINFO','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT, CHKSCOPECMDSQL) Values   ('VSDTXINFO', 'Điện thông báo từ VSD', 'Manage the notification messages from VSD', 'SELECT C.* 
FROM (
    SELECT L.* , TO_CHAR(L.TIMECREATED, ''DD/MM/RRRR'') DATECREATE, TO_CHAR(L.TIMECREATED, ''HH24:MI:SS'')  TIMECREATE, C.<@CDCONTENT> DESCRIPTION, DTL.FLDVAL VSDORDERID, DTL2.FLDVAL REAS
    FROM VSDTRFLOG L 
    LEFT JOIN (SELECT REFAUTOID, FLDVAL FROM VSDTRFLOGDTL WHERE FLDNAME = ''VSDORDERID'') DTL ON L.AUTOID = DTL.REFAUTOID
    LEFT JOIN (SELECT REFAUTOID, FLDVAL FROM VSDTRFLOGDTL WHERE FLDNAME = ''REAS'') DTL2 ON L.AUTOID = DTL2.REFAUTOID
    LEFT JOIN (SELECT TRFCODE, TYPE, DESCRIPTION CDCONTENT, EN_DESCRIPTION EN_CDCONTENT FROM VSDTRFCODE) C ON L.FUNCNAME = C.TRFCODE AND C.TYPE = ''INF''
    WHERE L.FUNCNAME NOT LIKE ''%.ACK'' AND L.FUNCNAME NOT LIKE ''%.NAK''
) C
WHERE 0 = 0', 'VSDTXINFO', 'VSDTXINFO', 'AUTOID DESC', '', 0, 5000, 'Y', 30, 'NYNNYYNN', 'Y', 'T', '', 'N', '', '');COMMIT;