SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('ST9950_1','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT, CHKSCOPECMDSQL) Values   ('ST9950_1', 'Tra cứu điện thông báo từ VSD (518-598)', 'Manage notification messages from VSD (518-598)', 'SELECT DT.* 
FROM
(
    SELECT TRF.AUTOID, TRF.REFMSGID, TO_CHAR(TRF.TIMECREATED, ''DD/MM/RRRR'') TIMECREATED, TO_CHAR(TRF.TIMECREATED, ''HH24:MI:SS'') TIMECREATED_TIME,
        MAX(CASE WHEN TRFLOG.FLDNAME = ''DETAIL'' THEN TRFLOG.FLDVAL ELSE '''' END) ORDERID,
        MAX(CASE WHEN TRFLOG.FLDNAME = ''REAS'' THEN TRFLOG.FLDVAL ELSE '''' END) REAS
    FROM 
    (
        SELECT * FROM VSDTRFLOG WHERE FUNCNAME = ''598.000.''
        UNION ALL 
        SELECT * FROM VSDTRFLOGHIST WHERE FUNCNAME = ''598.000.''
    ) TRF,
    (
        SELECT * FROM VSDTRFLOGDTL
        UNION ALL
        SELECT * FROM VSDTRFLOGDTLHIST
    ) TRFLOG
    WHERE TRF.AUTOID = TRFLOG.REFAUTOID
    GROUP BY TRF.AUTOID, TRF.REFMSGID, TRF.TIMECREATED, TO_CHAR( TRF.TIMECREATED, ''HH24:MI:SS'')
) DT
WHERE 0 = 0', 'ST9950_1', 'frmMT518', '', '    ', 0, 5000, 'Y', 30, 'NNNNYYYNNNN', 'Y', 'T', '', 'N', '', '');COMMIT;