SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('CORPACTION','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT, CHKSCOPECMDSQL) Values   ('CORPACTION', 'Thông tin tra cứu sự kiện quyền', 'Manage corporate actions', 'SELECT A.CDCONTENT VSDMSGTYPE, INF.AUTOID, INF.CAMASTID AS VSDMSGID, INF.SYMBOL, INF.BEGINDATE, INF.ENDDATE, INF.DESCRIPTION, INF.NUMBERINFORMATION, INF.DATETYPE,
(CASE WHEN SB.TRADEPLACE = ''001'' THEN ''0002''
	  WHEN SB.TRADEPLACE = ''002'' THEN ''0001''
	  WHEN SB.TRADEPLACE = ''005'' THEN ''0003''
	  WHEN SB.TRADEPLACE = ''010'' THEN ''0004''
	  ELSE ''0008''
END) TRADEPLACE
FROM 
(
	SELECT * FROM VSD_MT564_INF
	UNION ALL
	SELECT * FROM VSD_MT564_INF_HIST
)INF
LEFT JOIN (SELECT * FROM ALLCODE WHERE CDNAME = ''VSDMSGTYPE_564'') A ON INF.VSDMSGTYPE = A.CDVAL
LEFT JOIN SBSECURITIES SB On SB.SYMBOL = INF.SYMBOL
', 'CORPACTION', 'frmMaster', 'AUTOID DESC', '    ', 0, 5000, 'N', 30, '', 'Y', 'T', '', 'N', '', '');COMMIT;