SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('CORPACTION_BPUT','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT, CHKSCOPECMDSQL) Values   ('CORPACTION_BPUT', 'Thông tin tra cứu sự kiện quyền', 'Manage corporate actions', 'SELECT A.CDCONTENT VSDMSGTYPE, AUTOID, CAMASTID AS VSDMSGID, SYMBOL, BEGINDATE, ENDDATE, DESCRIPTION, NUMBERINFORMATION, DATETYPE
FROM 
(
	SELECT * FROM VSD_MT564_INF
	UNION ALL
	SELECT * FROM VSD_MT564_INF_HIST
)INF
LEFT JOIN (SELECT * FROM ALLCODE WHERE CDNAME = ''VSDMSGTYPE_564'') A ON INF.VSDMSGTYPE = A.CDVAL
WHERE INF.VSDMSGTYPE = ''BPUT''', 'CORPACTION', 'frmMaster', 'AUTOID DESC', '    ', 0, 5000, 'N', 30, '', 'Y', 'T', '', 'N', '', '');COMMIT;