SET DEFINE OFF;
CREATE OR REPLACE TRIGGER TRG_TBL_BALANCE_LOG_BEFORE 
 BEFORE
  INSERT
 ON tbl_balance_log
REFERENCING NEW AS NEW OLD AS OLD
 FOR EACH ROW
BEGIN
  :NEW.autoid := seq_TBL_BALANCE_LOG.NEXTVAL;
END;
-- End of
/
