SET DEFINE OFF;
CREATE OR REPLACE TRIGGER TRG_TBL_TRANS_LOG_BEFORE 
 BEFORE
  INSERT
 ON tbl_trans_log
REFERENCING NEW AS NEW OLD AS OLD
 FOR EACH ROW
BEGIN
  :NEW.autoid := seq_TBL_TRANS_LOG.NEXTVAL;
END;
-- End of
/
