SET DEFINE OFF;
CREATE OR REPLACE TRIGGER TRG_TBL_TRANSFER_LOG_BEFORE 
 BEFORE
  INSERT
 ON tbl_transfer_log
REFERENCING NEW AS NEW OLD AS OLD
 FOR EACH ROW
BEGIN
  :NEW.autoid := seq_tbl_transfer_log.NEXTVAL;
END;
/
